# Generated by Django 6.0.5 on 2026-06-30 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cadplan", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="placedobject",
            name="outside_wall",
            field=models.BooleanField(default=False),
        ),
    ]
