# Generated by Django 6.0.5 on 2026-06-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("netbox_cadplan", "0002_placedobject_outside_wall"),
    ]

    operations = [
        migrations.AddField(
            model_name="planzone",
            name="source_polygon",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
